AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  Exclude:
    - '**/bin/**/*'
    - '**/log/**/*'
    - '**/tmp/**/*'
    - '**/vedor/**/'
    - 'Gemfile'
    - 'config.ru'
    - 'Rakefile'
    - 'db/schema.rb'
    - 'spec/application_helper.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.7.1

Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/seeds.rb'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'config/application.rb'
    - '**/spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true