# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rake', '~> 13.0.0'

gem 'i18n', '~> 1.8.0'
gem 'config', '~> 2.2.0'

gem 'dry-initializer', '~> 3.0.0'
gem 'dry-validation', '~> 1.5.0'

gem 'activesupport', '~> 6.0.0', require: false

gem 'pry', '~> 0.13.0'

group :development, :test do
  gem 'pry-byebug', '~> 3.9.0'

  gem 'rspec', '~> 3.9.0'
  gem 'fabrication', '~> 2.21.0'
end