db:
  user: postgres
  password: notsecure
  database: hero_rider_development
redis:
  db: 1
  sidekiq_db: 2
psn:
  v1:
    auth:
      url: ''
    trophies:
      url: ''
    game_trophies:
      url: ''
      endpoint: ''
    profile:
      url: ''
      endpoint: ''
    threads:
      url: ''
  v2:
    trophies:
      url: ''
      endpoints:
        user_trophies: ''
        game_trophies: ''
telegram:
  bot_name: ''
  bot_token: ''
  admin_chat_id: # should be integer
  main_chat_id: # should be integer
  screenshot_worker: ''
