web:
  fqdn: <%= ENV.fetch('FQDN') %>
db:
  port: <%= ENV.fetch('DB_PORT') %>
  host: <%= ENV.fetch('DB_HOST') %>
  user: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  database: hero_rider_production
redis:
  port: <%= ENV.fetch('REDIS_PORT') %>
  db: <%= ENV.fetch('REDIS_DB') %>
  sidekiq_db: <%= ENV.fetch('REDIS_SIDEKIQ_DB') %>
psn:
  auth:
    url: <%= ENV.fetch('TROPHY_AUTH_URL') %>
  trophies:
    url: <%= ENV.fetch('TROPHY_TROPHIES_URL') %>
  game_trophies:
    url: <%= ENV.fetch('TROPHY_GAME_TROPHIES_URL') %>
    endpoint: <%= ENV.fetch('TROPHY_GAME_TROPHIES_ENDPOINT') %>
  profile:
    url: <%= ENV.fetch('TROPHY_PROFILE_URL') %>
    endpoint: <%= ENV.fetch('TROPHY_PROFILE_ENDPOINT') %>
  threads:
    url: <%= ENV.fetch('TROPHY_THREADS_URL') %>
telegram:
  bot_token: <%= ENV.fetch('TELEGRAM_BOT_TOKEN') %>
  admin_chat_id: <%= ENV.fetch('TELEGRAM_ADMIN_CHAT_ID') %>
  main_chat_id: <%= ENV.fetch('TELEGRAM_MAIN_CHAT_ID') %>
  screenshot_worker: <%= ENV.fetch('TELEGRAM_SCREENSHOT_WORKER_NAME') %>
