web:
  fqdn: <%= ENV.fetch('FQDN') %>
db:
  port: <%= ENV.fetch('DB_PORT') %>
  host: <%= ENV.fetch('DB_HOST') %>
  user: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  database: hero_rider_production
redis:
  port: <%= ENV.fetch('REDIS_PORT') %>
  db: <%= ENV.fetch('REDIS_DB') %>
  sidekiq_db: <%= ENV.fetch('REDIS_SIDEKIQ_DB') %>
psn:
  v1:
    auth:
      url: <%= ENV.fetch('V1_TROPHY_AUTH_URL') %>
    trophies:
      url: <%= ENV.fetch('V1_TROPHY_TROPHIES_URL') %>
    game_trophies:
      url: <%= ENV.fetch('V1_TROPHY_GAME_TROPHIES_URL') %>
      endpoint: <%= ENV.fetch('V1_TROPHY_GAME_TROPHIES_ENDPOINT') %>
    profile:
      url: <%= ENV.fetch('V1_TROPHY_PROFILE_URL') %>
      endpoint: <%= ENV.fetch('V1_TROPHY_PROFILE_ENDPOINT') %>
    threads:
      url: <%= ENV.fetch('V1_TROPHY_THREADS_URL') %>
  v2:
    auth:
      url: <%= ENV.fetch('V2_TROPHY_AUTH_URL') %>
      endpoints:
        code: <%= ENV.fetch('V2_TROPHY_AUTH_CODE_ENDPOINT') %>
        token: <%= ENV.fetch('V2_TROPHY_AUTH_TOKEN_ENDPOINT') %>
    trophies:
      url: <%= ENV.fetch('V2_TROPHY_TROPHIES_URL') %>
      endpoints:
        user_trophies: <%= ENV.fetch('V2_TROPHY_TROPHIES_USER_ENDPOINT') %>
        game_trophies: <%= ENV.fetch('V2_TROPHY_TROPHIES_GAME_ENDPOINT') %>
    profile:
      url: <%= ENV.fetch('V2_TROPHY_PROFILE_URL') %>
      endpoints:
        friends: <%= ENV.fetch('V2_TROPHY_PROFILE_FRIENDS_ENDPOINT') %>
        profile_info: <%= ENV.fetch('V2_TROPHY_PROFILE_INFO_ENDPOINT') %>
        user_ids: <%= ENV.fetch('V2_TROPHY_PROFILE_USER_IDS_ENDPOINT') %>
        search: <%= ENV.fetch('V2_TROPHY_PROFILE_SEARCH_ENDPOINT') %>
telegram:
  bot_name: <%= ENV.fetch('TELEGRAM_BOT_NAME') %>
  bot_token: <%= ENV.fetch('TELEGRAM_BOT_TOKEN') %>
  admin_chat_id: <%= ENV.fetch('TELEGRAM_ADMIN_CHAT_ID') %>
  main_chat_id: <%= ENV.fetch('TELEGRAM_MAIN_CHAT_ID') %>
  screenshot_worker: <%= ENV.fetch('TELEGRAM_SCREENSHOT_WORKER_NAME') %>
