db:
  user: postgres
  password: notsecure
  database: hero_rider_test
redis:
  db: 3
  sidekiq_db: 4
psn:
  v1:
    auth:
      url: ''
    trophies:
      url: ''
    game_trophies:
      url: ''
      endpoint: ''
    profile:
      url: ''
      endpoint: ''
    threads:
      url: ''
  v2:
    auth:
      url: ''
      endpoints:
        code: ''
        token: ''
    trophies:
      url: ''
      endpoints:
        user_trophies: ''
        game_trophies: ''
    profile:
      url: ''
      endpoints:
        friends: ''
        profile_info: ''
        user_ids: ''
        search: ''
telegram:
  bot_name: ''
  bot_token: ''
  admin_chat_id: # should be integer
  main_chat_id: # should be integer
  screenshot_worker: ''
