---
- hosts: db
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name:
          - postgresql
          - libpq-dev
          - python3-psycopg2
- hosts: db
  become: yes
  become_user: postgres
  gather_facts: no
  vars:
    database: hero_rider_production
    user: hero_rider
    password: '{{ database_password }}'
  tasks:
    - name: ensure database is created
      postgresql_db:
        name: '{{ database }}'
    - name: ensure user has access to database
      postgresql_user:
        db: '{{ database }}'
        name: '{{ user }}'
        password: '{{ password }}'
        priv: ALL
    - name: ensure user has no extra privileges
      postgresql_user:
        name: '{{ user }}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB
    - name: ensure no other user can access the database
      postgresql_privs:
        db: '{{ database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
