---
- hosts: redis
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name: redis-server
    - name: copy Redis configuration
      copy:
        src: redis/redis.conf
        dest: /etc/redis/redis.conf
      notify:
        - restart redis
    - name: Ensure Redis is running and enabled on boot
      service: "name=redis-server state=started enabled=yes"
  handlers:
    - name: restart redis
      service:
        name: redis-server
        state: restarted