---
- hosts: ufw
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name: ufw
    - name: allow ssh connections
      ufw:
        rule: limit
        port: ssh
        proto: tcp
        comment: 'Rate limit for openssh server'
    - name: allow connections via Nginx
      ufw:
        rule: allow
        name: 'Nginx Full'
    - name: enable firewall
      ufw:
        state: enabled