---
name: New commit to master notification
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            Heads up! Hero Rider just get updated!
            Updates: ${{ github.event.head_commit.message }}
            Look what <a href="https://github.com/Lokideos/hero_rider/commit/${{ github.sha }}">changed</a>
